apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: hmpps-tier-dev
    prometheus: cloud-platform
  name: hmpps-tier-dev-sqs
  namespace: hmpps-tier-dev
spec:
  groups:
  - name: hmpps-tier-dev-SQS
    rules:
    - alert: SQS-events-dlq-not-empty
      annotations:
        message: SQS Deadletter queue - {{ $labels.queue_name }} has {{ $value }} messages
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NDSS/pages/2963734549/Tiering+Run+book
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name="Digital-Prison-Services-dev-hmpps_tier_offender_events_queue_dl"} offset 5m) by (queue_name) > 0
      for: 10m
      labels:
        severity: digital-prison-service-dev

