---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: activities-dev.prison.service.justice.gov.uk
  namespace: activities-dev
spec:
  secretName: activities-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - activities-dev.prison.service.justice.gov.uk
