apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c100-application-metabase-admin
  namespace: c100-application-metabase
subjects:
  - kind: Group
    name: "github:family-justice"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
