apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-fum-cert
  namespace: ubi-prod
spec:
  secretName: prod-fum-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - find-unclaimed-court-money.service.justice.gov.uk
  - admin.find-unclaimed-court-money.service.justice.gov.uk