kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-book-secure-move-api-dev-admin
  namespace: hmpps-book-secure-move-api-dev
subjects:
  - kind: Group
    name: "github:pecs-developers"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
