---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: manage-recalls-prod

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: manage-recalls-prod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: manage-recalls-prod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
