---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nomis-user-roles-api-prod-admin
  namespace: nomis-user-roles-api-prod
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
