---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomis-user-roles-api-prod-cert
  namespace: nomis-user-roles-api-prod
spec:
  secretName: nomis-user-roles-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - nomis-user-roles-api.prison.service.justice.gov.uk
