kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-platform-app-commuter-webapp-xhibit-prod-admin
  namespace: data-platform-app-commuter-webapp-xhibit-prod
subjects:
  - kind: Group
    name: "github:commuter-webapp-xhibit-admin-team"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: github:analytics-hq
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
