apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: ppud-replacement-prod
  namespace: ppud-replacement-prod
spec:
  secretName: ppud-replacement-prod-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - manage-recalls.hmpps.service.justice.gov.uk
    - manage-recalls-ui.hmpps.service.justice.gov.uk
    - manage-recalls-api.hmpps.service.justice.gov.uk
