apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: laa-crime-maat-test
spec:
  limits:
  - default:
      cpu: 2000m
      memory: 4000Mi
    defaultRequest:
      cpu: 1000m
      memory: 1000Mi
    type: Container
