apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-reporting-cert
  namespace: soc-staging
spec:
  secretName: staging-reporting-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - 4.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
  - staging.reporting.hmcts-risk-assurance-operating-controls.service.justice.gov.uk