---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circleci
  namespace: laa-crime-means-assessment-dev
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "pods/log"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
      - "update"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: laa-crime-means-assessment-dev
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: laa-crime-means-assessment-dev
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
