kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: polygraph-offender-management-admin
  namespace: polygraph-offender-management
subjects:
  - kind: Group
    name: "github:polygraph-statistics-application"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
