kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dwf-prototype-admin
  namespace: dwf-prototype
subjects:
  - kind: Group
    name: "github:dwf-prototype"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
