kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rob-sandbox-admin
  namespace: rob-sandbox
subjects:
  - kind: Group
    name: "github:designers"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
