---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prisoner-from-nomis-cert
  namespace: hmpps-prisoner-from-nomis-migration-preprod
spec:
  secretName: prisoner-from-nomis-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prisoner-nomis-migration-preprod.hmpps.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomis-sync-dashboard-preprod.hmpps.service.justice.gov.uk
  namespace: hmpps-prisoner-from-nomis-migration-preprod
spec:
  secretName: nomis-sync-dashboard-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - nomis-sync-dashboard-preprod.hmpps.service.justice.gov.uk
