kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: philpayne-sandbox-admin
  namespace: philpayne-sandbox
subjects:
  - kind: Group
    name: "github:laa-ccms-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
