kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hale-platform-dev-admin
  namespace: hale-platform-dev
subjects:
  - kind: Group
    name: "github:jotw-content-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
