apiVersion: v1
kind: Namespace
metadata:
  name: demo-updated-moj-template-project
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Platforms"
    cloud-platform.justice.gov.uk/slack-channel: "operations-engineering-team"
    cloud-platform.justice.gov.uk/application: "Gov.UK Prototype Kit"
    cloud-platform.justice.gov.uk/owner: "operations-engineering: platforms@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/demo-updated-moj-template-project"
    cloud-platform.justice.gov.uk/team-name: "operations-engineering"
    cloud-platform.justice.gov.uk/review-after: ""
