---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-it-incident-hub-cert
  namespace: hmpps-it-incident-hub-dev
spec:
  secretName: hmpps-it-incident-hub-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - it-incident-hub-dev.hmpps.service.justice.gov.uk
