---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-external-users-api-cert
  namespace: hmpps-external-users-api-dev
spec:
  secretName: hmpps-external-users-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - external-users-api-dev.hmpps.service.justice.gov.uk
