kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-remand-and-sentencing-api-dev-admin
  namespace: hmpps-remand-and-sentencing-api-dev
subjects:
  - kind: Group
    name: "github:farsight-devs"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
