kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ap-gold-scorecard-form-prod-admin
  namespace: ap-gold-scorecard-form-prod
subjects:
  - kind: Group
    name: "github:analytical-platform"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
