apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: probation-search
  namespace: hmpps-probation-search-prod
spec:
  secretName: probation-search-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - probation-search-prod.hmpps.service.justice.gov.uk