apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chaps-staging-cert
  namespace: chaps-staging
spec:
  secretName: chaps-staging-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - staging.chaps.apps.live.cloud-platform.service.justice.gov.uk