kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dex-alistair-helloworld-admin
  namespace: dex-alistair-helloworld
subjects:
  - kind: Group
    name: "github:dex-engage"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
