---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: create-and-vary-a-licence-api.hmpps.service.justice.gov.uk
  namespace: create-and-vary-a-licence-api-prod
spec:
  secretName: create-and-vary-a-licence-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - create-and-vary-a-licence-api.hmpps.service.justice.gov.uk
