kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: makeaplea-preprod-admin
  namespace: makeaplea-preprod
subjects:
  - kind: Group
    name: "github:pet"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
