kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cccd-dev-dart-team
  namespace: cccd-dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  resourceNames: ["port-forward-pod"]
  verbs: ["get"]
