apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chaps-production-cert
  namespace: chaps-production
spec:
  secretName: chaps-production-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - production.chaps.apps.live.cloud-platform.service.justice.gov.uk