apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: ppud-replacement-dev
  namespace: ppud-replacement-dev
spec:
  secretName: ppud-replacement-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - manage-recalls-dev.hmpps.service.justice.gov.uk
    - manage-recalls-ui-dev.hmpps.service.justice.gov.uk
    - manage-recalls-api-dev.hmpps.service.justice.gov.uk
    - ppud-replacement-dashboards.hmpps.service.justice.gov.uk
    - ppud-replacement-bandiera.hmpps.service.justice.gov.uk
