kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bucket-data-uploader-dev-admin
  namespace: bucket-data-uploader-dev
subjects:
  - kind: Group
    name: "github:probation-data-engineering"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
