apiVersion: v1
kind: Namespace
metadata:
  name: data-eng-uploader-prototype
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "data_engineers"
    cloud-platform.justice.gov.uk/application: "Gov.UK Prototype Kit"
    cloud-platform.justice.gov.uk/owner: "Prison and Probation Data Engineering: platforms@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/data-eng-uploader-prototype"
    cloud-platform.justice.gov.uk/team-name: "prison-probation-data-engineering"
    cloud-platform.justice.gov.uk/review-after: ""
