apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: hmpps-manage-intelligence-preprod

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: circleci
  namespace: hmpps-manage-intelligence-preprod
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: hmpps-manage-intelligence-preprod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
