apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: hmpps-tier-to-delius-update.service.justice.gov.uk
  namespace: hmpps-tier-to-delius-update-prod
spec:
  secretName: hmpps-tier-to-delius-update-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - hmpps-tier-to-delius-update.service.justice.gov.uk
