---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: send-legal-mail-to-prisons-dev-admin
  namespace: send-legal-mail-to-prisons-dev
subjects:
  - kind: Group
    name: "github:farsight-devs"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dps-ingress-manager
  namespace: send-legal-mail-to-prisons-dev
subjects:
  - kind: ServiceAccount
    name: dps-ingress-manager
    namespace: dps-management-dev
roleRef:
  kind: ClusterRole
  name: dps-ingress-manager
  apiGroup: rbac.authorization.k8s.io
