---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: send-legal-mail-to-prisons-dev

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: send-legal-mail-to-prisons-dev
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "prometheusrules"
    verbs:
      - "*"

