apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: editor-tls-wildcard
  namespace: formbuilder-saas-live
spec:
  secretName: editor-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - 'moj-forms-editor.service.justice.gov.uk'
