kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ntollstreamlit-dev-admin
  namespace: ntollstreamlit-dev
subjects:
  - kind: Group
    name: "github:analytical-platform"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
