---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-allocations-cert
  namespace: workforce-management-dev
spec:
  secretName: hmpps-allocations-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-allocations-dev.hmpps.service.justice.gov.uk
