---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-ui-certificate
  namespace: hmpps-digital-prison-reporting-mi-preprod
spec:
  secretName: hmpps-digital-prison-reporting-mi-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - digital-prison-reporting-mi-preprod.hmpps.service.justice.gov.uk
    - digital-prison-reporting-mi-ui-preprod.hmpps.service.justice.gov.uk
