---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cd-serviceaccount
  namespace: laa-test-viewer
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "pods/log"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
      - "update"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "replicasets"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cd-serviceaccount
  namespace: laa-test-viewer
subjects:
  - kind: ServiceAccount
    name: cd-serviceaccount
    namespace: laa-test-viewer
roleRef:
  kind: Role
  name: cd-serviceaccount
  apiGroup: rbac.authorization.k8s.io