apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: laa-apply-for-legalaid-production

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: laa-apply-for-legalaid-production
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "HorizontalPodAutoscaler"
    verbs:
      - "patch"
      - "get"
      - "update"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
      - "apps"
      - "networking.k8s.io"
      - "batch"
    resources:
      - "deployments"
      - "cronjobs"
      - "ingresses"
      - "statefulsets"
      - "replicasets"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
