apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: probation-search-es
  namespace: probation-offender-search-preprod
spec:
  secretName: probation-search-es-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - probation-search-es-preprod.hmpps.service.justice.gov.uk