kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mayowa-hello-world-test-dev-admin
  namespace: mayowa-hello-world-test-dev
subjects:
  - kind: Group
    name: "github:laa-get-access"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
