apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ccq-staging-cert
  namespace: laa-estimate-financial-eligibility-for-legal-aid-production
spec:
  secretName: ccq-staging-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - staging.check-your-client-qualifies-for-legal-aid.service.gov.uk
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ccq-production-cert
  namespace: laa-estimate-financial-eligibility-for-legal-aid-production
spec:
  secretName: ccq-production-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - check-your-client-qualifies-for-legal-aid.service.gov.uk
---