kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ap-app-poc-bde-admin
  namespace: ap-app-poc-bde
subjects:
  - kind: Group
    name: "github:analytical-platform"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
