kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-cla-end-to-end-tests-admin
  namespace: laa-cla-end-to-end-tests
subjects:
  - kind: Group
    name: "github:laa-get-access"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
