apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: dso-monitoring-prod
  labels:
    role: alert-rules
  name: prometheus-custom-rules-offender-assessment-api
spec:
  groups:
  - name: application-rules
    rules:
    - alert: offender-assessment-api-down
      expr: |-
        probe_http_status_code{instance="offender-assessment-api-prod"}!=200
      for: 5m
      labels:
        severity: <custom_severity_level>
      annotations:
        message: Offender Assessment API has not responded in the last 5 minutes.        