kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-feedback-and-support-dev-admin
  namespace: hmpps-feedback-and-support-dev
subjects:
  - kind: Group
    name: "github:dps-core"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
