---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: hmpps-prisoner-to-nomis-update-preprod
spec:
  limits:
    - default:
        cpu: 2000m
        memory: 1024Mi
      defaultRequest:
        cpu: 10m
        memory: 512Mi
      type: Container
