kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: incident-management-dev-admin
  namespace: incident-management-dev
subjects:
  - kind: Group
    name: "github:modernisation-platform"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
