apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: allocation-manager-certificate
  namespace: offender-management-staging
spec:
  secretName: allocation-manager-hostname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - dev.service.justice.gov.uk
