apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: wmt-redirect-cert
  namespace: hmpps-workload-prod
spec:
  secretName: wmt-redirect-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - wmt.service.justice.gov.uk
