apiVersion: v1
kind: Namespace
metadata:
  name: courtfines-prod
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
    cloud-platform.justice.gov.uk/environment-name: "production"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMCTS"
    cloud-platform.justice.gov.uk/slack-channel: "pet"
    cloud-platform.justice.gov.uk/application: "Court fines"
    cloud-platform.justice.gov.uk/owner: "pet: pet@hmcts.net"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/hmcts-courtfines"
    cloud-platform.justice.gov.uk/team-name: "pet"
    cloud-platform.justice.gov.uk/review-after: ""
