---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-auth-staging-admin
  namespace: hmpps-auth-staging
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
