apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: sign-in-staging.hmpps.service.justice.gov.uk
  namespace: hmpps-auth-staging
spec:
  secretName: hmpps-auth-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - sign-in-staging.hmpps.service.justice.gov.uk
