kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: soc-reporting-dev-admin
  namespace: soc-reporting-dev
subjects:
  - kind: Group
    name: "github:dex-engage"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
