kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: probation-tiering-dev-admin
  namespace: probation_tiering_dev
subjects:
  - kind: Group
    name: "github:manage-a-sentence"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: probation_tiering_dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: probation-tiering-dev-circleci
  namespace: probation_tiering_dev
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: probation_tiering_dev
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
