apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: probation_tiering_dev
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1500Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
