apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: data-platform-app-mags-returners-sankey-s3-dev
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
