kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-infox-dev-admin
  namespace: laa-infox-dev
subjects:
  - kind: Group
    name: "github:laa-aws-infrastructure"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
