kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: make-recall-decision-ui-dev-admin
  namespace: make-recall-decision-ui-dev
subjects:
  - kind: Group
    name: "github:making-recall-decision"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
