---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: make-recall-decision-ui-dev

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: make-recall-decision-ui-dev
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: make-recall-decision-ui-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: make-recall-decision-ui-dev
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "prometheusrules"
      - "servicemonitors"

    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci-prometheus
  namespace: make-recall-decision-ui-dev
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: make-recall-decision-ui-dev
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
