apiVersion: v1
kind: Namespace
metadata:
  name: disclosure-checker-production
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
    cloud-platform.justice.gov.uk/environment-name: "production"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/application: "Check when to disclose cautions or convictions"
    cloud-platform.justice.gov.uk/owner: "Cross Justice Delivery: crossjusticedelivery@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/disclosure-checker"
    cloud-platform.justice.gov.uk/slack-channel: "disclosure-checker"
    cloud-platform.justice.gov.uk/team-name: "family-justice"
