apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: cla-frontend-production-cert
  namespace: laa-cla-frontend-production
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - cases.civillegaladvice.service.gov.uk
