apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: restricted-patients-dev.hmpps.service.justice.gov.uk
  namespace: hmpps-restricted-patients-dev
spec:
  secretName: hmpps-restricted-patients-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - restricted-patients-dev.hmpps.service.justice.gov.uk