---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prison-visits-admin-cert
  namespace: visit-someone-in-prison-frontend-svc-dev
spec:
  secretName:  prison-visits-admin-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prison-visits-admin-dev.prison.service.justice.gov.uk