kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ap-judicial-reviews-app-prod-admin
  namespace: ap-judicial-reviews-app-prod
subjects:
  - kind: Group
    name: "github:analytical-platform"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
