---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: send-legal-mail-api-preprod.prison.service.justice.gov.uk
  namespace: send-legal-mail-to-prisons-preprod
spec:
  secretName: send-legal-mail-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - send-legal-mail-api-preprod.prison.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: send-legal-mail-preprod.prison.service.justice.gov.uk
  namespace: send-legal-mail-to-prisons-preprod
spec:
  secretName: send-legal-mail-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - send-legal-mail-preprod.prison.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: check-rule39-mail-preprod.prison.service.justice.gov.uk
  namespace: send-legal-mail-to-prisons-preprod
spec:
  secretName: check-rule39-mail-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - check-rule39-mail-preprod.prison.service.justice.gov.uk
