---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-nomis-mapping-service-cert
  namespace: hmpps-nomis-mapping-service-preprod
spec:
  secretName: hmpps-nomis-mapping-service-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk
