kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-platform-app-mags-returners-sankey-s3-prod-admin
  namespace: data-platform-app-mags-returners-sankey-s3-prod
subjects:
  - kind: Group
    name: "github:cajs"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: github:analytics-hq
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
