---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: manage-offences-api-dev.hmpps.service.justice.gov.uk
  namespace: manage-offences-api-dev
spec:
  secretName: manage-offences-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - manage-offences-api-dev.hmpps.service.justice.gov.uk
