kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-dpr-poc-dev-admin
  namespace: hmpps-dpr-poc-dev
subjects:
  - kind: Group
    name: "github:hmpps-digital-prison-reporting"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
