kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dpr-nomis-port-forwarder-admin
  namespace: dpr-nomis-port-forwarder
subjects:
  - kind: Group
    name: "github:dpr-developers"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
