apiVersion: v1
kind: ServiceAccount
metadata:
  name: nomis-port-forwarder
  namespace: dpr-nomis-port-forwarder
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nomis-port-forwarder
  namespace: dpr-nomis-port-forwarder
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "update"
      - "delete"
      - "list"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nomis-port-forwarder
  namespace: dpr-nomis-port-forwarder
subjects:
  - kind: ServiceAccount
    name: nomis-port-forwarder
    namespace: dpr-nomis-port-forwarder
roleRef:
  kind: Role
  name: nomis-port-forwarder
  apiGroup: rbac.authorization.k8s.io
