---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-adjustments-folder-api-dev-cert
  namespace: hmpps-adjustments-folder-dev
spec:
  secretName: hmpps-adjustments-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - adjustments-api-dev.hmpps.service.justice.gov.uk
