apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-strengths-based-needs-assessments-preprod.hmpps.service.justice.gov.uk
  namespace: hmpps-strengths-based-needs-assessments-preprod
spec:
  secretName: hmpps-strengths-based-needs-assessments-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-strengths-based-needs-assessments-preprod.hmpps.service.justice.gov.uk
