kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elsa-relevant-search-production-admin
  namespace: elsa-relevant-search-production
subjects:
  - kind: Group
    name: "github:family-justice"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
