apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: elsa-relevant-search-certificate-production
  namespace: elsa-relevant-search-production
spec:
  secretName: elsa-relevant-search-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - search-information-about-legal-problems.service.justice.gov.uk
