apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laa-court-data-ui
  namespace: laa-court-data-ui-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: laa-court-data-ui
  namespaceSelector:
    matchNames:
      - laa-court-data-ui-dev
  endpoints:
    - port: metrics
      interval: 15s
