apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels: 
    openpolicyagent.org/webhook: "ignore"
    component: kube-system
    cloud-platform.justice.gov.uk/slack-channel: "cloud-platform"
