kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-recalls-dev-admin
  namespace: manage-recalls-dev
subjects:
  - kind: Group
    name: "github:ppud-replacement-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
