---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-manage-users-api-preprod-cert
  namespace: hmpps-manage-users-preprod
spec:
  secretName: hmpps-manage-users-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - manage-users-api-preprod.hmpps.service.justice.gov.uk
