---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: help-with-prison-visits.hmpps.service.justice.gov.uk
  namespace: help-with-prison-visits-prod
spec:
  secretName: help-with-prison-visits-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - help-with-prison-visits.hmpps.service.justice.gov.uk
