---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-manage-adjudications-prod-admin
  namespace: hmpps-manage-adjudications-prod
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-production-releases"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-manage-adjudications-prod-admin
  namespace: hmpps-manage-adjudications-prod
subjects:
  - kind: Group
    name: "github:dps-core"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dps-ingress-manager
  namespace: hmpps-manage-adjudications-prod
subjects:
  - kind: ServiceAccount
    name: dps-ingress-manager
    namespace: dps-management-prod
roleRef:
  kind: ClusterRole
  name: dps-ingress-manager
  apiGroup: rbac.authorization.k8s.io
