---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-micro-frontend-component-header-cert
  namespace: hmpps-micro-frontend-components-dev
spec:
  secretName: hmpps-micro-frontend-component-header-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - micro-frontend-component-header.hmpps.service.justice.gov.uk
