apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-historical-prisoner-cert
  namespace: hmpps-historical-prisoner-dev
spec:
  secretName: hmpps-historical-prisoner-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - historical-prisoner-dev.prison.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-historical-prisoner-api-cert
  namespace: hmpps-historical-prisoner-dev
spec:
  secretName: hmpps-historical-prisoner-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - historical-prisoner-api-dev.prison.service.justice.gov.uk
