kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approved-premises-prototype-admin
  namespace: approved-premises-prototype
subjects:
  - kind: Group
    name: "github:approved-premises-prototype"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
