---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: education-skills-work-employment-preprod-admin
  namespace: education-skills-work-employment-preprod
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:education-skills-work-employment"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dps-ingress-manager
  namespace: education-skills-work-employment-preprod
subjects:
  - kind: ServiceAccount
    name: dps-ingress-manager
    namespace: dps-management-preprod
roleRef:
  kind: ClusterRole
  name: dps-ingress-manager
  apiGroup: rbac.authorization.k8s.io
