apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: prisoner-employability-preprod.prison.service.justice.gov.uk
  namespace: education-skills-work-employment-preprod
spec:
  secretName: prisoner-employability-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - prisoner-employability-preprod.prison.service.justice.gov.uk
