apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: education-skills-work-employment-preprod.prison.service.justice.gov.uk
  namespace: education-skills-work-employment-preprod
spec:
  secretName: education-skills-work-employment-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - eswe-preprod.prison.service.justice.gov.uk
