kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: davidread-helloworld-dev-admin
  namespace: davidread-helloworld-dev
subjects:
  - kind: Group
    name: "github:cloud-platform-test"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
