apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sign-in.hmpps.service.justice.gov.uk
  namespace: hmpps-auth-prod
spec:
  secretName: hmpps-auth-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - sign-in.hmpps.service.justice.gov.uk
