kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eligibility-estimate-admin
  namespace: eligibility-estimate
subjects:
  - kind: Group
    name: "github:laa-eligibility-calculator"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
