apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: pcms-api-dev
  namespace: hmpps-pin-phone-monitor-dev
spec:
  secretName: pcms-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - pcms-api-dev.prison.service.justice.gov.uk
