apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: education-agg.prison.service.justice.gov.uk
  namespace: education-skills-work-employment-prod
spec:
  secretName: education-agg-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - education-agg.prison.service.justice.gov.uk
