---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: domains-cert
  namespace: maintenance-pages
spec:
  secretName: domains-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - maintenance-page.cloud-platform.service.justice.gov.uk
  - nomisqc.justice.gov.uk
  - civil-eligibility-calculator.justice.gov.uk
