kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-prisoner-education-admin
  namespace: hmpps-prisoner-education
subjects:
  - kind: Group
    name: "github:education-skills-work-employment"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
