apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laa-court-data-api-production-cert
  namespace: laa-court-data-api-production
spec:
  secretName: laa-court-data-api-production-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - court-data-api.service.justice.gov.uk