---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prisoner-transactions-dev.hmpps.service.justice.gov.uk
  namespace: prisoner-transactions-dev
spec:
  secretName: prisoner-transactions-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prisoner-transactions-dev.hmpps.service.justice.gov.uk
