apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
      - "apps"
      - "networking.k8s.io"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
      - "watch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
roleRef:
  kind: Role
  name: "{{ .Name }}"
  apiGroup: rbac.authorization.k8s.io
