---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: activities-preprod2.prison.service.justice.gov.uk
  namespace: hmpps-activities-management-preprod
spec:
  secretName: activities-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - activities-preprod2.prison.service.justice.gov.uk

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: activities-api-preprod2.prison.service.justice.gov.uk
  namespace: hmpps-activities-management-preprod
spec:
  secretName: activities-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - activities-api-preprod2.prison.service.justice.gov.uk
