kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apply-for-legal-aid-prototype-admin
  namespace: apply-for-legal-aid-prototype
subjects:
  - kind: Group
    name: "github:laa-apply-for-legal-aid"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
