apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: calculate-journey-variable-payments-dev
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2048Mi
    defaultRequest:
      cpu: 100m
      memory: 1024Mi
    type: Container
