kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-world-carlos-dev-admin
  namespace: hello-world-carlos-dev
subjects:
  - kind: Group
    name: "github:dex-engage"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
