apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: court-probation-preprod-cert
  namespace: court-probation-preprod
spec:
  secretName: court-probation-preprod-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prepare-a-case-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
