apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: court-probation-preprod-cert
  namespace: court-probation-prod
spec:
  secretName: court-probation-preprod-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - court-list-splitter-preprod.hmpps.service.justice.gov.uk
