apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preprod.offender-risk-profiler.service.justice.gov.uk
  namespace: offender-categorisation-dev
spec:
  secretName: offender-risk-profiler-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - preprod.offender-risk-profiler.service.justice.gov.uk
