apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-fum-cert
  namespace: ubi-dev
spec:
  secretName: dev-fum-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - development.find-unclaimed-court-money.service.justice.gov.uk
  - admin.development.find-unclaimed-court-money.service.justice.gov.uk