---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: manage-offences.hmpps.service.justice.gov.uk
  namespace: manage-offences-prod
spec:
  secretName: manage-offences-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - manage-offences.hmpps.service.justice.gov.uk
