kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-estimate-financial-eligibility-for-legal-aid-uat-admin
  namespace: laa-estimate-financial-eligibility-for-legal-aid-uat
subjects:
  - kind: Group
    name: "github:laa-estimate-eligibility"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
