apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resettlement-passport-api-dev-cert
  namespace: hmpps-resettlement-passport-dev
spec:
  secretName: hmpps-resettlement-passport-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-resettlement-passport-prototype-api-dev.hmpps.service.justice.gov.uk

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resettlement-passport-ui-dev-cert
  namespace: hmpps-resettlement-passport-dev
spec:
  secretName: hmpps-resettlement-passport-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-resettlement-passport-prototype-ui-dev.hmpps.service.justice.gov.uk