kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: track-a-query-metabase-admin
  namespace: track-a-query-metabase
subjects:
  - kind: Group
    name: "github:correspondence"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: track-a-query-metabase
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: track-a-query-metabase
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: track-a-query-metabase
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
