apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: track-a-query-metabase
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2000Mi
    defaultRequest:
      cpu: 20m
      memory: 250Mi
    type: Container
