kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-architect-info-admin
  namespace: laa-architect-info
subjects:
  - kind: Group
    name: "github:laa-technical-architects"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
