kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ppud-replacement-preprod-admin
  namespace: ppud-replacement-preprod
subjects:
  - kind: Group
    name: "github:ppud-replacement-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
