apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: ppud-replacement-preprod
  namespace: ppud-replacement-preprod
spec:
  secretName: ppud-replacement-preprod-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - manage-recalls-preprod.hmpps.service.justice.gov.uk
    - manage-recalls-ui-preprod.hmpps.service.justice.gov.uk
    - manage-recalls-api-preprod.hmpps.service.justice.gov.uk
