kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-help-with-prison-visits-development-admin
  namespace: hmpps-help-with-prison-visits-development
subjects:
  - kind: Group
    name: "github:hmpps-help-with-prison-visits"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
