apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laa-court-data-api-dev-cert
  namespace: laa-court-data-api-dev
spec:
  secretName: laa-court-data-api-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - dev.court-data-api.service.justice.gov.uk