apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: assure-hmrc-data-certificate
  namespace: laa-assure-hmrc-data-production
spec:
  secretName: assure-hmrc-data-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - assure-hmrc-data.service.justice.gov.uk
