apiVersion: v1
kind: Namespace
metadata:
  name: opg-gt-test-prototype
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "OPG"
    cloud-platform.justice.gov.uk/slack-channel: "gt-test"
    cloud-platform.justice.gov.uk/application: "Gov.UK Prototype Kit"
    cloud-platform.justice.gov.uk/owner: "Greg Tyler: platforms@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/opg-gt-test-prototype"
    cloud-platform.justice.gov.uk/team-name: "gt-test-team"
    cloud-platform.justice.gov.uk/review-after: ""
