kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-assess-risks-and-needs-prototypes-admin
  namespace: hmpps-assess-risks-and-needs-prototypes
subjects:
  - kind: Group
    name: "github:hmpps-assess-risks-and-needs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
