apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-ref-app
  namespace: cloud-platform-reference-app-dev
spec:
  secretName: ref-app-ssl
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - refapp.live-2.cloud-platform.service.justice.gov.uk
