apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-reporting-cert
  namespace: soc-production
spec:
  secretName: production-reporting-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - 6.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
  - reporting.hmcts-risk-assurance-operating-controls.service.justice.gov.uk