apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-entry-cert
  namespace: soc-production
spec:
  secretName: production-entry-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - 5.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
  - entry.hmcts-risk-assurance-operating-controls.service.justice.gov.uk