kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interventions-design-history-admin
  namespace: interventions-design-history
subjects:
  - kind: Group
    name: "github:interventions"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
