---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: book-a-prison-visit-dev-admin
  namespace: book-a-prison-visit-dev
subjects:
  - kind: Group
    name: "github:book-a-prison-visit"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
