apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: preprod.hmpps-tier-to-delius-update.service.justice.gov.uk
  namespace: hmpps-tier-to-delius-update-preprod
spec:
  secretName: hmpps-tier-to-delius-update-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - preprod.hmpps-tier-to-delius-update.service.justice.gov.uk
