kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-intelligence-test-admin
  namespace: manage-intelligence-test
subjects:
  - kind: Group
    name: "github:dps-soct-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
