apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: manage-intelligence-api-test.prison.service.justice.gov.uk
  namespace: manage-intelligence-test
spec:
  secretName: manage-intelligence-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - manage-intelligence-api-test.prison.service.justice.gov.uk
