kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: recalldecisions-prototype-admin
  namespace: recalldecisions-prototype
subjects:
  - kind: Group
    name: "github:happygeneralist"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
