kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: moj-prototype-admin
  namespace: moj-prototype
subjects:
  - kind: Group
    name: "github:operations-engineering"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
