kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apply-for-compensation-prototype-dev-admin
  namespace: apply-for-compensation-prototype-dev
subjects:
  - kind: Group
    name: "github:cica"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
