kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-manage-supervisions-prod-admin
  namespace: hmpps-manage-supervisions-prod
subjects:
  - kind: Group
    name: "github:hmpps-probation-end-to-end"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
