apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: manage-supervisions.hmpps.service.justice.gov.uk
  namespace: hmpps-manage-supervisions-prod
spec:
  secretName: hmpps-manage-supervisions-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - manage-supervisions.hmpps.service.justice.gov.uk