apiVersion: v1
kind: Namespace
metadata:
  name: manage-recalls-prod
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
    cloud-platform.justice.gov.uk/environment-name: "prod"
    cloud-platform.justice.gov.uk/namespace-name: "manage-recalls-prod"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "ppud-replacement-devs"
    cloud-platform.justice.gov.uk/slack-alert-channel: "ppud-replacement-alerts-nonprod"
    cloud-platform.justice.gov.uk/application: "Manage a Recall (MaR)"
    cloud-platform.justice.gov.uk/owner: "The PPUD Replacement Team: ppud-replacement-tech@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/?q=manage-recalls"
    cloud-platform.justice.gov.uk/team-name: "ppud-replacement-devs"
    cloud-platform.justice.gov.uk/review-after: ""
