---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: book-a-prison-visit-preprod

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: book-a-prison-visit-preprod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: book-a-prison-visit-preprod
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: book-a-prison-visit-preprod
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "prometheusrules"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci-prometheus
  namespace: book-a-prison-visit-preprod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: book-a-prison-visit-preprod
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
