---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: raise-an-incident

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: raise-an-incident
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: raise-an-incident
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: raise-an-incident
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "prometheusrules"
      - "servicemonitors"
    verbs:
      - "*"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "networkpolicies"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci-prometheus
  namespace: raise-an-incident
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: raise-an-incident
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
