kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: courts-local-scorecard-dev-admin
  namespace: courts-local-scorecard-dev
subjects:
  - kind: Group
    name: "github:central-digital-developers"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
