kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-licenses-prototype-admin
  namespace: hmpps-licenses-prototype
subjects:
  - kind: Group
    name: "github:hmpps-licenses-prototype"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
