apiVersion: v1
kind: Namespace
metadata:
  name: ppud-replacement-dev
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    cloud-platform.justice.gov.uk/namespace-name: "ppud-replacement-dev"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "ppud-replacement-devs"
    cloud-platform.justice.gov.uk/slack-alert-channel: "ppud-replacement-alerts-nonprod"
    cloud-platform.justice.gov.uk/application: "PPUD Replacement"
    cloud-platform.justice.gov.uk/owner: "PPUD Replacement: ppud-replacement-tech@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/manage-recalls"
    cloud-platform.justice.gov.uk/team-name: "ppud-replacement-devs"
    cloud-platform.justice.gov.uk/review-after: ""
