apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: sandbox-ppse-cert
  namespace: sandbox-ppse
spec:
  secretName: sandbox-ppse-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - ppse-sample-ui-dev.hmpps.service.justice.gov.uk
