kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-view-court-data-prototype-admin
  namespace: laa-view-court-data-prototype
subjects:
  - kind: Group
    name: "github:laa-assess-a-claim"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
