kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaps-dev-admin
  namespace: chaps-dev
subjects:
  - kind: Group
    name: "github:dotnet"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
