kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anasir_test_hello_world-admin
  namespace: anasir_test_hello_world
subjects:
  - kind: Group
    name: "github:check-my-diary"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
