---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-education-and-work-plan-api-dev.prison.service.justice.gov.uk
  namespace: hmpps-education-and-work-plan-dev
spec:
  secretName:  hmpps-education-and-work-plan-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-education-and-work-plan-api-dev.prison.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  hmpps-education-and-work-plan-dev.prison.service.justice.gov.uk
  namespace: hmpps-education-and-work-plan-dev
spec:
  secretName:  hmpps-education-and-work-plan-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    -  hmpps-education-and-work-plan-dev.prison.service.justice.gov.uk
