kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remand-and-sentencing-prod-admin
  namespace: remand-and-sentencing-prod
subjects:
  - kind: Group
    name: "github:farsight-devs"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
