kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-tier-to-delius-update-dev-admin
  namespace: hmpps-tier-to-delius-update-dev
subjects:
  - kind: Group
    name: "github:manage-a-sentence"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
