kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apshinytest-dev-admin
  namespace: apshinytest-dev
subjects:
  - kind: Group
    name: "github:analytics-hq"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
