---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus-pushgateway-monitoring
  namespace: ppud-replacement-preprod
spec:
  podSelector:
    matchLabels:
      app: prometheus-pushgateway
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            component: monitoring
