---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-consider-a-recall-email-dev-admin
  namespace: hmpps-consider-a-recall-email-dev
subjects:
  - kind: Group
    name: "github:making-recall-decision"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
