apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: court-probation-dev-cert
  namespace: court-probation-dev
spec:
  secretName: court-probation-dev-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - prepare-a-case-dev.apps.live-1.cloud-platform.service.justice.gov.uk

