apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-authorization-server-dev.hmpps.service.justice.gov.uk
  namespace: hmpps-authorization-server-dev
spec:
  secretName: hmpps-auth-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-authorization-server-dev.hmpps.service.justice.gov.uk
