kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cla-reform-design-admin
  namespace: cla-reform-design
subjects:
  - kind: Group
    name: "github:cla-reform-design"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
