kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-incentives-tool-admin
  namespace: hmpps-incentives-tool
subjects:
  - kind: Group
    name: "github:hmpps-incentives"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
