name: terraform-tools

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          tfsec_args: --force-all-dirs --no-module-downloads --soft-fail -m=HIGH -e=github-repositories-private,github-branch_protections-require_signed_commits,aws-iam-no-policy-wildcards,aws-ecr-enforce-immutable-repository,aws-rds-enable-performance-insights-encryption
          sarif_file: tfsec.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
