apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-configuration
  namespace: check-financial-eligibility-uat
  annotations:
    nginx.org/server-tokens: "False"
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
