kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opg-lpa-fd-prototype-admin
  namespace: opg-lpa-fd-prototype
subjects:
  - kind: Group
    name: "github:opg"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
