apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-internal
  namespace: manage-my-prison-dev
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-internal
  namespace: manage-my-prison-dev
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - s3
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-internal
  namespace: manage-my-prison-dev
subjects:
  - kind: ServiceAccount
    name: pod-internal
    namespace: manage-my-prison-dev
roleRef:
  kind: Role
  name: pod-internal
  apiGroup: rbac.authorization.k8s.io
