apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: manage-my-prison-dev
spec:
  secretName: cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - manage-my-prison-dev.prison.service.justice.gov.uk
